name: MediaTek-immortalwrt-master

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '固件类型'
        required: true
        type: choice
        default: 'MT7981-master'
        options:
          - 'MT7981-master'
          - 'MT7981-2410'
          - 'MT7981-2512'
          - 'MT7981-padavanonly'
          - 'MT7981-2410-ap'
          - 'MT7987-master'
      source:
        description: '选择源码'
        required: true
        type: choice
        default: 'https://github.com/Ranx5/immortalwrt'
        options:
          - 'https://github.com/Ranx5/immortalwrt'
          - 'https://github.com/immortalwrt/immortalwrt'
          - 'https://github.com/padavanonly/immortalwrt-mt798x-6.6'
      branch:
        description: '选择配置'
        required: true
        type: choice
        default: 'master'
        options:
          - 'master'
          - 'master-mt7987'
          - 'openwrt-24.10'
          - 'openwrt-25.12'
          - 'openwrt-24.10-6.6'
      config:
        description: '选择配置'
        required: true
        type: choice
        default: 'Configs/mt7981_main_diff.config'
        options:
          - 'Configs/mt3600be_imm_diff.config'
          - 'Configs/mt7981_ap_diff.config'
          - 'Configs/mt7981_main_diff.config'
          - 'Configs/mt7981_2410_diff.config'
          - 'Configs/padavanonly_mt798x.config'
          - 'Configs/mt7981_imm24_ap.config'
      script2:
        description: '选择脚本2'
        required: true
        type: choice
        default: 'Scripts/diy-mt7981-imm-part2.sh'
        options:
          - 'Scripts/diy-mt7981-imm-part2.sh'
          - 'Scripts/diy-mt7981-imm24-part2.sh'
          - 'Scripts/diy-nothing.sh'
      script3:
        description: '选择脚本3'
        required: true
        type: choice
        default: 'Scripts/preset-meta2.sh'
        options:
          - 'Scripts/preset-meta2.sh'
          - 'Scripts/diy-nothing.sh'
      lan_ip:
        description: '设置LAN口IP'
        required: true
        type: string
        default: '192.168.32.1'
env:
  REPO_URL: ${{ github.event.inputs.source }}
  REPO_BRANCH: ${{ github.event.inputs.branch }}
  CONFIG_FILE: ${{ github.event.inputs.config }}
  DIY_P1_SH: Scripts/diy-imm-part1.sh
  DIY_P2_SH: ${{ github.event.inputs.script2 }}
  DIY_P3_SH: ${{ github.event.inputs.script3 }}
  LAN_IP: ${{ github.event.inputs.lan_ip }}
  CACHE_TOOLCHAIN: true
  UPLOAD_RELEASE: true
  FIRMWARE_TAG: ${{ github.event.inputs.tag }}
  TZ: Asia/Shanghai
  WHOAMI: Rancho

jobs:
  Build:
    runs-on: ubuntu-22.04

    outputs:
      COMMIT_AUTHOR: ${{ steps.clone.outputs.COMMIT_AUTHOR }}
      COMMIT_DATE: ${{ steps.clone.outputs.COMMIT_DATE }}
      COMMIT_MESSAGE: ${{ steps.clone.outputs.COMMIT_MESSAGE }}
      COMMIT_HASH: ${{ steps.clone.outputs.COMMIT_HASH }}
      DEVICE_TARGET: ${{ steps.variable.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ steps.variable.outputs.DEVICE_SUBTARGET }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Free Disk Space
      id: clear
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "$TZ"

    - name: Clone Source Code
      id: clone
      run: |
        df -hT $GITHUB_WORKSPACE
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
        COMMIT_AUTHOR=$(git show -s --date=short --format="作者: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
        COMMIT_DATE=$(git show -s --date=short --format="时间: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_OUTPUT
        COMMIT_MESSAGE=$(git show -s --date=short --format="内容: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT
        
    - name: Load custom feeds
      run: |
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH    
    
    - name: Load Custom Configuration
      run: |
        [ -e files ] && mv files $OPENWRT_PATH/files
        chmod +x $DIY_P2_SH
        chmod +x $DIY_P3_SH
        cd openwrt
        sed -i "s/192.168.1.1/$LAN_IP/g" package/base-files/files/bin/config_generate
        echo "Set LAN IP Address: $LAN_IP"
        $GITHUB_WORKSPACE/$DIY_P2_SH
        $GITHUB_WORKSPACE/$DIY_P3_SH
        
    - name: Generate Variables
      id: variable
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        make defconfig
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_OUTPUT
        DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_OUTPUT
        
    - name: Download DL Package
      run: |
        cd $OPENWRT_PATH
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Cache Toolchain
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}
        prefix: ${{ env.OPENWRT_PATH }}
    
    - name: Compile Firmware
      id: compile
      run: |
        cd $OPENWRT_PATH
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Check Space Usage
      if: (!cancelled())
      run: df -hT

    - name: Organize Files
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        cat sha256sums
        cp $OPENWRT_PATH/.config build.config
        find $OPENWRT_PATH/bin/packages -type f \( -name "*.ipk" -o -name "*.apk" \) -exec mv -f {} packages \;
        tar -zcf Packages.tar.gz packages
        rm -rf packages feeds.buildinfo version.buildinfo
        find "$PWD" -mindepth 1 -type d -exec rm -rf {} +
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware To Release
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@v1.15.0
      with:
        name: R${{ env.DATE }} for ${{ env.FIRMWARE_TAG }}
        allowUpdates: true
        tag: ${{ env.FIRMWARE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          **This is Temporary Firmware for ${{ env.FIRMWARE_TAG }}**
          - ${{ env.CONFIG_FILE }}
          - Lan IP Address: ${{ env.LAN_IP }}
          ### 🧊 固件版本
          - 固件编译前最后一次➦[主源码](${{ env.REPO_URL }})更新记录
          - ${{ env.COMMIT_AUTHOR }}
          - ${{ env.COMMIT_DATE }}
          - ${{ env.COMMIT_MESSAGE }}
          - ${{ env.COMMIT_HASH }}
