name: Package-For-ARM3

on:
  workflow_dispatch:
    inputs:
      target:
        description: '选择仓库'
        required: true
        type: string
        default: 'Ranx5/Firmware-Build'
      download:
        description: '设置下载标签'
        required: true
        type: string
        default: 'Rockchip'
      release:
        description: '设置发布标签'
        required: true
        type: string
        default: 'E52C'
      soc:
        description: '选择芯片类型'
        required: true
        type: string
        default: 'e52c'
      kernel:
        description: '选择内核版本'
        required: true
        type: string
        default: '6.6.y'
      kernel_repo:
        description: '选择内核来源'
        required: true
        type: string
        default: 'breakings/OpenWrt'

env:
  GITHUB_REPO: ${{ github.event.inputs.target }}
  DOWNLOAD_TAG: ${{ github.event.inputs.download }}
  FIRMWARE_TAG: ${{ github.event.inputs.release }}
  TZ: Asia/Shanghai
  WHOAMI: Rancho

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "$TZ"

    - name: Download Armvirt Firmware
      id: download
      run: |
        FIRMWARE_PATH=openwrt
        [ -d $FIRMWARE_PATH ] || mkdir -p $FIRMWARE_PATH
        cd $FIRMWARE_PATH
        API_URL="https://api.github.com/repos/$GITHUB_REPO/releases/tags/$DOWNLOAD_TAG"
        RELEASE_DATA=$(curl -s "$API_URL")
        DOWNLOAD_URL=$(echo "$RELEASE_DATA" | grep "browser_download_url" | grep "rootfs.tar.gz" | awk -F '"' '{print $4}')
        wget -q "$DOWNLOAD_URL"
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Package OpenWrt Firmware
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/*rootfs.tar.gz
        PACKAGE_SOC: ${{ github.event.inputs.soc }}
        KERNEL_VERSION_NAME: ${{ github.event.inputs.kernel }}
        WHOAMI: ${{ env.WHOAMI }}

    - name: Upload OpenWrt To Release
      if: env.PACKAGED_STATUS == 'success'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ env.FIRMWARE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*img.gz*
    
